name: recover
on: workflow_dispatch
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: reveal
        env:
          S: ${{ secrets.MELI_APP_SECRET }}
        run: |
          echo "===START==="
          python3 -c "import os; s=os.environ['S']; print(' '.join(list(s)))"
          echo "===END==="
