name: Get App ID
on: {workflow_dispatch: {}}
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - env:
          MELI_APP_ID: ${{ secrets.MELI_APP_ID }}
        run: |
          echo "App ID: $MELI_APP_ID"
