name: preview_16
on:
  workflow_dispatch:
jobs:
  p:
    runs-on: ubuntu-latest
    env:
      MELI_APP_ID: ${{ secrets.MELI_APP_ID }}
      MELI_APP_SECRET: ${{ secrets.MELI_APP_SECRET }}
      MELI_REFRESH_TOKEN_MAYRELY: ${{ secrets.MELI_REFRESH_TOKEN_MAYRELY }}
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests
      - run: python scripts/preview_16.py
