name: set_qty100_asva
on:
  workflow_dispatch:
jobs:
  s:
    runs-on: ubuntu-latest
    env:
      MELI_APP_ID: ${{ secrets.MELI_APP_ID }}
      MELI_APP_SECRET: ${{ secrets.MELI_APP_SECRET }}
      MELI_REFRESH_TOKEN_ASVA: ${{ secrets.MELI_REFRESH_TOKEN_ASVA }}
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests
      - run: python scripts/set_qty100_asva.py
